server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hcx?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8

mybatis:
    mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl